# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dbtempo < Formula
  desc "Database performance monitoring and query analysis CLI"
  homepage "https://dbtempo.com"
  version "0.0.360"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dbtempo/dbtempo/releases/download/v0.0.360/dbtempo_darwin_x86_64.tar.gz"
      sha256 "26f014a408169f50b1795bde68940d914a90eccc6383d2ff4be9f206b26d1f67"

      define_method(:install) do
        bin.install "dbtempo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dbtempo/dbtempo/releases/download/v0.0.360/dbtempo_darwin_arm64.tar.gz"
      sha256 "70d716d722e24ba22a3f5a1349a424b9bff0e954c5e7d5bfedba86a3c8de7e97"

      define_method(:install) do
        bin.install "dbtempo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dbtempo/dbtempo/releases/download/v0.0.360/dbtempo_linux_x86_64.tar.gz"
      sha256 "d3259d55647dfcdbfdd0d9be4e0e588e4a06c431ef0f4b6491f38d5f3b6ba887"
      define_method(:install) do
        bin.install "dbtempo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dbtempo/dbtempo/releases/download/v0.0.360/dbtempo_linux_arm64.tar.gz"
      sha256 "a95d7c6b3dfd4e8412e0fece6ec1f611f77edb058fa1f4bd95809d33ae4fedea"
      define_method(:install) do
        bin.install "dbtempo"
      end
    end
  end

  test do
    system "#{bin}/dbtempo version"
  end
end
